# Generated by Django 5.1 on 2025-02-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evapotranspiraciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_lote', models.IntegerField(null=True)),
                ('milimetrosMCuadrado', models.FloatField()),
                ('fecha', models.DateTimeField()),
            ],
        ),
    ]
