# Generated by Django 5.1 on 2025-02-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HumedadTerreno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_bancal', models.IntegerField(null=True)),
                ('porcentaje', models.IntegerField()),
                ('fecha', models.DateTimeField()),
            ],
        ),
    ]
