# Generated by Django 5.1 on 2024-12-02 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancal', '0001_initial'),
        ('lotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bancal',
            name='lote',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lotes.lote'),
        ),
    ]
