# Generated by Django 5.1 on 2025-02-20 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuraciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametros', models.IntegerField()),
                ('fk_sensores', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sensores.sensores')),
            ],
        ),
    ]
