# Generated by Django 5.1 on 2025-02-20 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datos_meteorologicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorAbs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_lote', models.IntegerField(null=True)),
                ('fecha', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Sensores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_sensores', models.CharField(max_length=200)),
                ('fk_datos_metereologicos_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datos_meteorologicos.datos_metereologicos')),
            ],
        ),
    ]
