# Generated by Django 5.1 on 2024-12-02 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantaciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantacion',
            old_name='id_bancal',
            new_name='bancal',
        ),
    ]
